### PR TITLE
fix: Added Django 4.0, Python 3.10, and DRF 3.13 support

### PR DESCRIPTION
**Pull request by john-whiting**
- Updated to add support for newest versions of python and dependencies.
- Updated tox tests to include the new versions
- Removed deprecated functions

### CODE REVIEW

**Comment by john-whiting** [comment]
Fixes Issue: #106

**Comment by andylamp** [comment]
@fitodic could you please approve this... unless there is any obvious reason not to?

**Comment by fitodic** [comment]
Hi, sorry for the delay. I just merged it and released [1.19.2](https://github.com/Styria-Digital/django-rest-framework-jwt/blob/master/CHANGELOG.md#1192-2022-01-08)

**Comment by n0mn0m** [comment]
Thank you @fitodic

**Pull request merged**
