### PR TITLE
refactor(views): remove serializer on response data

### PR DESCRIPTION
**Pull request by tchaguitos**
Removing serializer on response data 'JWT_RESPONSE_PAYLOAD_HANDLER' works

### CODE REVIEW

**Comment by fitodic** [comment]
@tchaguitos Thanks for your contribution!

Would you mind adding a [changelog](https://github.com/Styria-Digital/django-rest-framework-jwt/blob/master/CONTRIBUTING.md#changelog)?

**Comment by tchaguitos** [comment]
@fitodic 

hey!
i'm sorry for the delay. recently i'm little busy, but at this weekend i will write the changelog. greetings :)

**Comment by paymog** [comment]
@tchaguitos any updates? I'm running into this issue too while migrating from the unmaintained framework.

**Comment by paymog** [comment]
@fitodic is this PR missing anything other than a changelog entry? I'm happy to submit a new PR  myself if that would speed things up.

**Comment by tchaguitos** [comment]
@paymog i've been busy at last months and i just couldn't finish it :(

(but i believe that only the changelog is missing)

**Comment by fitodic** [comment]
@paymog @tchaguitos Yes, only the changelog is missing with a description of what changes were introduced and why. The changelog guidelines are documented in [`CONTRIBUTING.md`](https://github.com/Styria-Digital/django-rest-framework-jwt/blob/master/CONTRIBUTING.md#changelog).

**Comment by paymog** [comment]
See #22

**Comment by tchaguitos** [comment]
thanks @paymog :)

**Comment by tchaguitos** [comment]
@fitodic i'm closing this pull request...

**Pull request closed without merging**
