### PR TITLE
Fixing the status codes

### PR DESCRIPTION
**Pull request by creyD**
As I said in #79 I adjusted the status codes to return what is documented.

### CODE REVIEW

**Comment by fitodic** [comment]
@creyD Thanks for the PR 🙂 Would you mind adding a [changelog](https://github.com/Styria-Digital/django-rest-framework-jwt/blob/master/CONTRIBUTING.md#changelog) and pulling the lastest `master`? That should fix the pipeline.

**Comment by creyD** [comment]
@fitodic Sure! Sorry I didn't see the Contributing.md before.

**Comment by creyD** [comment]
Can you test it for you again? There was one test failing, but i don't think this is because of my changes. test_authentication.py Line 120 for reference.

**Comment by fitodic** [comment]
> Can you test it for you again? There was one test failing, but i don't think this is because of my changes. test_authentication.py Line 120 for reference.

If that's the one regarding sets and payload key's, it's already been fixed in #81. The only thing that remains is to pull the `master` branch and push the changes 🙂

**Comment by creyD** [comment]
Thanks for merging this so fast! When will there be a new release?

**Comment by fitodic** [comment]
> Thanks for merging this so fast! When will there be a new release?

[1.17.3](https://pypi.org/project/drf-jwt/1.17.3/) is available on PyPI 🙂

**Comment by creyD** [comment]
Thanks!

**Comment by dominik-bln** [comment]
Quick Feedback: This change was a bit surprising in a patch update because it alters the behaviour of the API, i. e. it is a breaking change. For us it hopefully only broke the tests, but changing the docs or putting this in a major update would have seemed more appropriate.

**Pull request merged**
