### PR TITLE
Fix/custom username payload

### PR DESCRIPTION
**Pull request by paolodamico**
Basically this PR introduces two fixes when `JWT_GET_USER_SECRET_KEY` method is overridden,
* If the payload contains a non-existent user, a validation error will be raised (same as when the method is not overridden). Previously, when this happened, an uncatched error from Django.
* The `jwt_get_secret_key` method will now use the `JWT_PAYLOAD_GET_USERNAME_HANDLER` configuration.

### CODE REVIEW

**Comment by fitodic** [comment]
Thanks for the PR! :+1:

**Comment by paolodamico** [comment]
Awesome! Could you publish to PyPI please?

**Comment by fitodic** [comment]
I thought I already did, but it seems the CI is still not able to push releases to PyPI. :thinking: 

Anyway, I just uploaded it to [PyPI](https://pypi.org/project/drf-jwt/1.15.2/). Sorry for the delay :slightly_smiling_face:

**Comment by paolodamico** [comment]
No worries, thank you so much 🙌

**Pull request merged**
