### PR TITLE
Use force_str to replace deprecated force_text

### PR DESCRIPTION
**Pull request by dominik-bln**

### CODE REVIEW

**Comment by dominik-bln** [comment]
@fitodic Did you close this on purpose? As far as I can tell this change is not included in the referenced merge

**Comment by fitodic** [comment]
> @fitodic Did you close this on purpose? As far as I can tell this change is not included in the referenced merge

Sorry, I accidentaly referenced this issue in the https://github.com/Styria-Digital/django-rest-framework-jwt/commit/b7296dcf6a8b93ae494974c8ba70b141369a4def. Thanks for calling it out :+1:

**Comment by fitodic** [comment]
I thought I reopened this PR when posting the last comment :thinking: 

Sorry, I'm more accustomed to GitLab than GItHub. Is there anything you have to do on your part to reopen it? Or better yet, could you include these changes in https://github.com/Styria-Digital/django-rest-framework-jwt/pull/45?

**Comment by dominik-bln** [comment]
> Sorry, I'm more accustomed to GitLab than GItHub.

I know the feeling 😄 

I'll add this to #45

**Comment by dominik-bln** [comment]
The changes are in #45 now.

**Comment by fitodic** [comment]
Terrific :+1: I've reopened https://github.com/Styria-Digital/django-rest-framework-jwt/issues/43 so you can link it in the PR and close it properly.

**Pull request closed without merging**
